### ISSUE TITLE
SpringUtil question

### ISSUE THREAD

**Issue by jjhesk** [facebook/rebound#55]
Would you explain to me how to understand these params by your sample app
```java
  // On each update of the spring value, we adjust the scale of the image view to match the
      // springs new value. We use the SpringUtil linear interpolation function mapValueFromRangeToRange
      // to translate the spring's 0 to 1 scale to a 100% to 50% scale range and apply that to the View
      // with setScaleX/Y. Note that rendering is an implementation detail of the application and not
      // Rebound itself. If you need Gingerbread compatibility consider using NineOldAndroids to update
      // your view properties in a backwards compatible manner.
      float mappedValue = (float) SpringUtil.mapValueFromRangeToRange(spring.getCurrentValue(), 0, 1, 1, 0.5);
```

At the end, I would like to apply the spring's 0 to 1 to 400dp to 100 dp in the layout height. Please let me know how to apply it into ```SpringUtil.mapValueFromRangeToRange(spring.getCurrentValue(), 0, 1, 1, 0.5);```. Thank you so much.

**Comment by jjhesk** [comment]
is the answer going to be

```SpringUtil.mapValueFromRangeToRange(spring.getCurrentValue(), 0, 1, 100, 400);``` ?

**Comment by willbailey** [comment]
If you want 0 to be 400 and 1 to be 100 then it would be:
SpringUtil.mapValueFromRangeToRange(spring.getCurrentValue(), 0, 1, 400, 100);

of course that's going to be px if you want dp you'll need to convert your dp to px values separately.

**Comment by jjhesk** [comment]
how do we make a conversion dynamically?

**Comment by jasleensingh** [comment]
If you have the values in a dimension values (400dp, 100dp) in an xml somewhere, you can use:
`int px = context.getResources().getDimensionPixelSize(<res-id>);`
to convert the dp value to pixels. Otherwise, there are a number of ways to do a direct conversion, one of which is:
`int px = (int) TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_DIP, <size_in_dp>, context.getResources().getDisplayMetrics());`
