### ISSUE TITLE
SequencerSpring

### ISSUE THREAD

**Issue by ppamorim** [facebook/rebound#60]
@willbailey What do you think about a sequencer Spring? It's similar of SpringChain but without any interaction with another springs. Look like:

    SpringSquencer().create()
      .add(0, new Spring())
      .add(1, new Spring(), 1000)
      .add(2, new Spring());

The first spring(at 0 index) will run, when this animation ends,  it will run the second spring(at index 1) and wait 1000 miliseconds to run the spring at index 2.

**Comment by willbailey** [comment]
If you want to write up the code for this I'll take a look. What's the use case you have in mind?

**Comment by willbailey** [comment]
Let me know if you have a pull request for this at some point. Closing this issue out.

**Comment by ppamorim** [comment]
Working a lot will :(

**Comment by amalChandran** [comment]
@ppamorim any update on the sequencer?
