### ISSUE TITLE
Does this lib work with markers/maps?

### ISSUE THREAD

**Issue by Ricardo1980** [facebook/rebound#62]
Hello,

Does this lib work with markers/maps?
I would like to see one of those anmations everytime I add a new marker.

Thanks.

**Comment by ppamorim** [comment]
I think it's possible, you can simple get the pin and transform the position. Look like:

    Marker m = map.addMarker(a);
    LatLng latlng = new LatLng();

    on spring update:
    latlng.setLatitude(X);
    latlng.setLongitude(Y);
    m.setPosition(latlng);

**Comment by Ricardo1980** [comment]
What about scale?
What I want to achueve is a small bouncing in scale (x and y) when I add the marker. Is that possible? 
Thanks.

**Comment by ppamorim** [comment]
It can be a problem because maps works with bitmap, but you can try to scale the bitmap of this marker.

**Comment by willbailey** [comment]
There's no reason it won't work with maps, but you may have to do some work to wire in the animations. I haven't looked into it myself, but would be curious to see if you get something working.
