### ISSUE TITLE
Make samples apk available

### ISSUE THREAD

**Issue by BugsBunnyBR** [facebook/rebound#70]
Hi, I would like to be able to download the samples apk.
I tried to compile the source code, but I just have the jdk 1.8 in my machine and #53 says it is not compatible with that..so, could you, please, make the samples apk available?

**Comment by willbailey** [comment]
You should get Java 1.7 working on your machine if you intend to do Android development. I would like to make the APKs available on the PlayStore at some point soon as well. Thanks!

**Comment by ppamorim** [comment]
+1

**Comment by chchgb** [comment]
try this, it fix the issue for me.

apply plugin: 'java'

sourceCompatibility = 1.7
targetCompatibility = 1.7
